In [1]:
import pandas as pd

In [17]:
with open('data/movies.dat','r') as f:
    movies_df = pd.DataFrame(l.rstrip().split('::') for l in f)

In [18]:
movies_df.head(20)

     0                                      1                             2
0    1                       Toy Story (1995)   Animation|Children's|Comedy
1    2                         Jumanji (1995)  Adventure|Children's|Fantasy
2    3                Grumpier Old Men (1995)                Comedy|Romance
3    4               Waiting to Exhale (1995)                  Comedy|Drama
4    5     Father of the Bride Part II (1995)                        Comedy
5    6                            Heat (1995)         Action|Crime|Thriller
6    7                         Sabrina (1995)                Comedy|Romance
7    8                    Tom and Huck (1995)          Adventure|Children's
8    9                    Sudden Death (1995)                        Action
9   10                       GoldenEye (1995)     Action|Adventure|Thriller
10  11         American President, The (1995)          Comedy|Drama|Romance
11  12     Dracula: Dead and Loving It (1995)                 Comedy|Horror
12  13                           Balto (1995)          Animation|Children's
13  14                           Nixon (1995)                         Drama
14  15                Cutthroat Island (1995)      Action|Adventure|Romance
15  16                          Casino (1995)                Drama|Thriller
16  17           Sense and Sensibility (1995)                 Drama|Romance
17  18                      Four Rooms (1995)                      Thriller
18  19  Ace Ventura: When Nature Calls (1995)                        Comedy
19  20                     Money Train (1995)                        Action

In [23]:
with open('data/users.dat','r') as f:
    users_df = pd.DataFrame(l.rstrip().split('::') for l in f)

In [24]:
users_df.head(20)

     0  1   2   3      4
0    1  F   1  10  48067
1    2  M  56  16  70072
2    3  M  25  15  55117
3    4  M  45   7  02460
4    5  M  25  20  55455
5    6  F  50   9  55117
6    7  M  35   1  06810
7    8  M  25  12  11413
8    9  M  25  17  61614
9   10  F  35   1  95370
10  11  F  25   1  04093
11  12  M  25  12  32793
12  13  M  45   1  93304
13  14  M  35   0  60126
14  15  M  25   7  22903
15  16  F  35   0  20670
16  17  M  50   1  95350
17  18  F  18   3  95825
18  19  M   1  10  48073
19  20  M  25  14  55113

In [26]:
ratings_df = pd.read_csv('data/training.csv')

In [29]:
ratings_df.describe()

                user          movie         rating     timestamp
count  800000.000000  800000.000000  800000.000000  8.000000e+05
mean     3403.097837    1849.257256       3.590479  9.683921e+08
std      1546.589028    1086.852485       1.120376  5.820931e+06
min       636.000000       1.000000       1.000000  9.567039e+08
25%      2035.000000    1028.000000       3.000000  9.641524e+08
50%      3507.000000    1788.000000       4.000000  9.675878e+08
75%      4695.000000    2750.000000       4.000000  9.746878e+08
max      6040.000000    3952.000000       5.000000  9.757673e+08

In [41]:
test_df = ratings_df.sort_values('timestamp', ascending=True)[-100000:]

In [42]:
test_df.count()

user         100000
movie        100000
rating       100000
timestamp    100000
dtype: int64

In [40]:
train_df = ratings_df.sort_values('timestamp', ascending=True)[:-100000]

In [44]:
train_df.head()

   user  movie  rating  timestamp
0  6040    858       4  956703932
1  6040    593       5  956703954
2  6040   2384       4  956703954
3  6040   1961       4  956703977
4  6040   2019       5  956703977

In [1]:
%load_ext autoreload
%autoreload 2

In [23]:
from src.team_recommender import MovieRecommender

In [24]:
mr = MovieRecommender()

Traceback (most recent call last):
  File "/usr/local/Cellar/apache-spark/2.1.0/libexec/python/pyspark/cloudpickle.py", line 107, in dump
    return Pickler.dump(self, obj)
  File "/Users/BirdPerson/anaconda/lib/python2.7/pickle.py", line 224, in dump
    self.save(obj)
  File "/Users/BirdPerson/anaconda/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/BirdPerson/anaconda/lib/python2.7/pickle.py", line 568, in save_tuple
    save(element)
  File "/Users/BirdPerson/anaconda/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/local/Cellar/apache-spark/2.1.0/libexec/python/pyspark/cloudpickle.py", line 214, in save_function
    self.save_function_tuple(obj)
  File "/usr/local/Cellar/apache-spark/2.1.0/libexec/python/pyspark/cloudpickle.py", line 251, in save_function_tuple
    save((code, closure, base_globals))
  File "/Users/BirdPerson/anaconda/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/BirdPerson/anaconda/lib/python2.7/pickle.py", line 554, in save_tuple
    save(element)
  File "/Users/BirdPerson/anaconda/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/BirdPerson/anaconda/lib/python2.7/pickle.py", line 606, in save_list
    self._batch_appends(iter(obj))
  File "/Users/BirdPerson/anaconda/lib/python2.7/pickle.py", line 639, in _batch_appends
    save(x)
  File "/Users/BirdPerson/anaconda/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/local/Cellar/apache-spark/2.1.0/libexec/python/pyspark/cloudpickle.py", line 214, in save_function
    self.save_function_tuple(obj)
  File "/usr/local/Cellar/apache-spark/2.1.0/libexec/python/pyspark/cloudpickle.py", line 251, in save_function_tuple
    save((code, closure, base_globals))
  File "/Users/BirdPerson/anaconda/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/BirdPerson/anaconda/lib/python2.7/pickle.py", line 554, in save_tuple
    save(element)
  File "/Users/BirdPerson/anaconda/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/BirdPerson/anaconda/lib/python2.7/pickle.py", line 606, in save_list
    self._batch_appends(iter(obj))
  File "/Users/BirdPerson/anaconda/lib/python2.7/pickle.py", line 639, in _batch_appends
    save(x)
  File "/Users/BirdPerson/anaconda/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/local/Cellar/apache-spark/2.1.0/libexec/python/pyspark/cloudpickle.py", line 214, in save_function
    self.save_function_tuple(obj)
  File "/usr/local/Cellar/apache-spark/2.1.0/libexec/python/pyspark/cloudpickle.py", line 251, in save_function_tuple
    save((code, closure, base_globals))
  File "/Users/BirdPerson/anaconda/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/BirdPerson/anaconda/lib/python2.7/pickle.py", line 554, in save_tuple
    save(element)
  File "/Users/BirdPerson/anaconda/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/BirdPerson/anaconda/lib/python2.7/pickle.py", line 606, in save_list
    self._batch_appends(iter(obj))
  File "/Users/BirdPerson/anaconda/lib/python2.7/pickle.py", line 642, in _batch_appends
    save(tmp[0])
  File "/Users/BirdPerson/anaconda/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/local/Cellar/apache-spark/2.1.0/libexec/python/pyspark/cloudpickle.py", line 411, in save_instancemethod
    obj=obj)
  File "/usr/local/Cellar/apache-spark/2.1.0/libexec/python/pyspark/cloudpickle.py", line 545, in save_reduce
    save(args)
  File "/Users/BirdPerson/anaconda/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/BirdPerson/anaconda/lib/python2.7/pickle.py", line 554, in save_tuple
    save(element)
  File "/Users/BirdPerson/anaconda/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/usr/local/Cellar/apache-spark/2.1.0/libexec/python/pyspark/cloudpickle.py", line 458, in save_inst
    save(stuff)
  File "/Users/BirdPerson/anaconda/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/BirdPerson/anaconda/lib/python2.7/pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "/Users/BirdPerson/anaconda/lib/python2.7/pickle.py", line 687, in _batch_setitems
    save(v)
  File "/Users/BirdPerson/anaconda/lib/python2.7/pickle.py", line 331, in save
    self.save_reduce(obj=obj, *rv)
  File "/usr/local/Cellar/apache-spark/2.1.0/libexec/python/pyspark/cloudpickle.py", line 563, in save_reduce
    save(state)
  File "/Users/BirdPerson/anaconda/lib/python2.7/pickle.py", line 286, in save
    f(self, obj) # Call unbound method with explicit self
  File "/Users/BirdPerson/anaconda/lib/python2.7/pickle.py", line 655, in save_dict
    self._batch_setitems(obj.iteritems())
  File "/Users/BirdPerson/anaconda/lib/python2.7/pickle.py", line 687, in _batch_setitems
    save(v)
  File "/Users/BirdPerson/anaconda/lib/python2.7/pickle.py", line 306, in save
    rv = reduce(self.proto)
  File "/Users/BirdPerson/anaconda/lib/python2.7/site-packages/py4j/java_gateway.py", line 1133, in __call__
    answer, self.gateway_client, self.target_id, self.name)
  File "/usr/local/Cellar/apache-spark/2.1.0/libexec/python/pyspark/sql/utils.py", line 63, in deco
    return f(*a, **kw)
  File "/Users/BirdPerson/anaconda/lib/python2.7/site-packages/py4j/protocol.py", line 323, in get_return_value
    format(target_id, ".", name, value))
Py4JError: An error occurred while calling o107.__getnewargs__. Trace:
py4j.Py4JException: Method __getnewargs__([]) does not exist
	at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:318)
	at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:326)
	at py4j.Gateway.invoke(Gateway.java:272)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:745)

PicklingError: Could not serialize object: Py4JError: An error occurred while calling o107.__getnewargs__. Trace:
py4j.Py4JException: Method __getnewargs__([]) does not exist
	at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:318)
	at py4j.reflection.ReflectionEngine.getMethod(ReflectionEngine.java:326)
	at py4j.Gateway.invoke(Gateway.java:272)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:214)
	at java.lang.Thread.run(Thread.java:745)